config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Create routes to remap controllers to easy urls.
     */
    $routes->connect('/bestellingen', ['controller' => 'PurchaseOrders']);
    $routes->connect('/bestellingen/:action/*', ['controller' => 'PurchaseOrders']);

    $routes->connect('/bestelregels', ['controller' => 'SuppliersProductsPurchaseOrders']);
    $routes->connect('/bestelregels/:action/*', ['controller' => 'SuppliersProductsPurchaseOrders']);

    $routes->connect('/leveranciers', ['controller' => 'Suppliers']);
    $routes->connect('/leveranciers/:action/*', ['controller' => 'Suppliers']);

    $routes->connect('/leverancier-producten', ['controller' => 'SuppliersProducts']);
    $routes->connect('/leverancier-producten/:action/*', ['controller' => 'SuppliersProducts']);

    $routes->connect('/gebruikers', ['controller' => 'Users']);
    $routes->connect('/gebruikers/:action/*', ['controller' => 'Users']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Table/PurchaseOrdersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\ORM\TableRegistry;
use Cake\Validation\Validator;

/**
 * PurchaseOrders Model
 *
 * @property \App\Model\Table\SuppliersTable&\Cake\ORM\Association\BelongsTo $Suppliers
 * @property \App\Model\Table\UsersTable&\Cake\ORM\Association\BelongsTo $Users
 * @property \App\Model\Table\SuppliersProductsTable&\Cake\ORM\Association\BelongsToMany $SuppliersProducts
 *
 * @method \App\Model\Entity\PurchaseOrder get($primaryKey, $options = [])
 * @method \App\Model\Entity\PurchaseOrder newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\PurchaseOrder[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\PurchaseOrder|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\PurchaseOrder saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\PurchaseOrder patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\PurchaseOrder[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\PurchaseOrder findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PurchaseOrdersTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('purchase_orders');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Suppliers', [
            'foreignKey' => 'supplier_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsToMany('SuppliersProducts', [
            'foreignKey' => 'purchase_order_id',
            'targetForeignKey' => 'suppliers_product_id',
            'joinTable' => 'suppliers_products_purchase_orders'
        ]);

        $this->hasMany('SuppliersProductsPurchaseOrders', [
            'foreignKey' => 'purchase_order_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->boolean('delivery')
            ->notEmptyString('delivery');

        $validator
            ->dateTime('delivery_moment')
            ->requirePresence('delivery_moment', 'create')
            ->notEmptyDateTime('delivery_moment');

        $validator
            ->decimal('delivery_cost')
            ->notEmptyString('delivery_cost');

        $validator
            ->decimal('total_amount')
            ->notEmptyString('total_amount');

        $validator
            ->scalar('comment')
            ->maxLength('comment', 255)
            ->allowEmptyString('comment');

        $validator
            ->boolean('closed')
            ->notEmptyString('closed');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['supplier_id'], 'Suppliers'));
        $rules->add($rules->existsIn(['user_id'], 'Users'));

        return $rules;
    }

    /**
     * beforeSave event to set delivery cost and total amount before saving.
     * This action is also called by SuppliersProductsPurchaseOrdersTable.php.
     */
    public function beforeSave(\Cake\Event\Event $event, $entity, $options)
    {
        $purchaseOrderSupplier = TableRegistry::getTableLocator()->get('Suppliers')->get($entity->supplier_id);
        $suppliersProductsPurchaseOrders = TableRegistry::getTableLocator()->get('SuppliersProductsPurchaseOrders')
            ->find('all')->where(['purchase_order_id' => $entity->id]);
        
        // initial values to zero.
        $entity->delivery_cost = 0;
        $entity->total_amount  = 0;

        // Add up all purchase order record totals.
        foreach($suppliersProductsPurchaseOrders as $suppliersProductsPurchaseOrder) {
            $entity->total_amount += $suppliersProductsPurchaseOrder->quantity * $suppliersProductsPurchaseOrder->price;
        }

        // Eventually add the possible delivery costs.
        if ($entity->delivery && $purchaseOrderSupplier->delivery) {
            // if ($entity->total_amount >= $purchaseOrderSupplier->delivery_cost_minimum) {
                // If there is no delivery_cost_until defined, or the total amount is smaller, add the delivery cost. 
                if ($purchaseOrderSupplier->delivery_cost_until === 0.0 || bccomp($entity->total_amount, $purchaseOrderSupplier->delivery_cost_until) == -1) {
                    $entity->delivery_cost = $purchaseOrderSupplier->delivery_cost;
                    $entity->total_amount += $entity->delivery_cost;
                }
            //} 
        }
    }
}

src/Controller/UsersController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Users Controller
 *
 * @property \App\Model\Table\UsersTable $Users
 *
 * @method \App\Model\Entity\User[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class UsersController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        // Always allow allow the registration and logout page.
        $this->Auth->allow(['register', 'logout']);
    }

    public function isAuthorized($user)
    {
        // Run controller specific authorisation checks if
        // the parent check is returning no access was given.
        if (parent::isAuthorized($user))
            return true;

        $action = $this->request->getParam('action');
        if (in_array($action, ['add','register', 'logout'])) {
            return true;
        }

        // All other actions require an user id.
        $id = $this->request->getParam('pass.0');
        if (!$id) {
            return false;
        }

        // Check that the account belongs to the current user.
        $account = $this->Users->findById($id)->first();

        return $account->id === $user['id'];
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['Roles']
        ];
        $users = $this->paginate($this->Users);

        $this->set(compact('users'));
    }

    /**
     * Login method
     * 
     *  @return \Cake\Http\Response|null
     */
    public function login()
    {
        if ($this->request->is('post')) {
            $user = $this->Auth->identify();
            // Only accept active users.
            if ($user && $user['active']) {
                $this->Auth->setUser($user);
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error('Your username or password is incorrect.');
        }
    }
    
    /**
     * Logout method
     *
     * @return \Cake\Http\Response|null
     **/
    public function logout()
    {
        $this->Flash->success('You are now logged out.');
        return $this->redirect($this->Auth->logout());
    }

    /**
     * View method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => ['Roles', 'PurchaseOrders', 'PurchaseOrders.Suppliers', 'PurchaseOrders.Users', 'SuppliersProductsPurchaseOrders', 'SuppliersProductsPurchaseOrders.Users', 'SuppliersProductsPurchaseOrders.SuppliersProducts', 'SuppliersProductsPurchaseOrders.SuppliersProducts.Products']
        ]);

        $this->set('user', $user);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            if ($this->Users->save($user)) {
                $this->Flash->success(__('The user has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'));
        }
        $roles = $this->Users->Roles->find('list', ['limit' => 200]);
        $this->set(compact('user', 'roles'));
    }

    /**
     * Register method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function register()
    {
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            if (isset($this->request->getData()['GDPR']) && $this->request->getData()['GDPR'] == 1) {
                $user = $this->Users->patchEntity($user, $this->request->getData(), [
                    // Disable modification of certain admin-only fields.
                    'accessibleFields' => [
                        'balance' => false,
                        'role_id' => false,
                        'active'  => false,
                    ]
                ]);
                if ($this->Users->save($user)) {
                    $this->Flash->success(__('The user has been saved.'));

                    return $this->redirect(['action' => 'login']);
                }
                $this->Flash->error(__('The user could not be saved. Please, try again.'));
            }
            else {
                $this->Flash->error(__('Please agree terms to register your account.'));
            }
        }
        $this->set(compact('user'));
    }

    /**
     * Edit method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => []
        ]);

        // check if the authenticated user is authorized to modify balance, role and active.
        $isAdmin = (AppController::isAuthorized($this->Auth->user()));
        
        if ($this->request->is(['patch', 'post', 'put'])) {
            if ($isAdmin) {
                $user = $this->Users->patchEntity($user, $this->request->getData());
            } else {
                $user = $this->Users->patchEntity($user, $this->request->getData(), [
                    // Disable modification of certain admin-only fields.
                    'accessibleFields' => [
                        'balance' => false,
                        'role_id' => false,
                        'active'  => false,
                    ]
                ]);
            }
            if ($this->Users->save($user)) {
                $this->Flash->success(__('The user has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'));
        }
        $roles = $this->Users->Roles->find('list', ['limit' => 200]);
        $this->set(compact('user', 'roles', 'isAdmin'));
    }

    /**
     * Delete method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $user = $this->Users->get($id);
        if ($this->Users->delete($user)) {
            $this->Flash->success(__('The user has been deleted.'));
        } else {
            $this->Flash->error(__('The user could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Users/add.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\User $user
 */
?>
<nav class="large-2 medium-3 columns" id="actions-sidebar">
    <?= $this->element('Menu/gebruiker-menu') ?>
</nav>
<div class="users form large-10 medium-9 columns content">
    <?= $this->Form->create($user) ?>
    <fieldset>
        <legend><?= __('Add User') ?></legend>
        <?php
            echo $this->Form->control('first_name');
            echo $this->Form->control('last_name');
            echo $this->Form->control('phone');
            echo $this->Form->control('email');
            echo $this->Form->control('iban');
            echo $this->Form->control('balance');
            echo $this->Form->control('password');
            echo $this->Form->control('role_id', ['options' => $roles]);
            echo $this->Form->control('active');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Users/edit.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\User $user
 */
?>
<nav class="large-2 medium-3 columns" id="actions-sidebar">
    <?= $this->element('Menu/gebruiker-menu') ?>
</nav>
<div class="users form large-10 medium-9 columns content">
    <?= $this->Form->create($user) ?>
    <fieldset>
        <legend><?= __('Edit User') ?></legend>
        <?php
            echo $this->Form->control('first_name');
            echo $this->Form->control('last_name');
            echo $this->Form->control('phone');
            echo $this->Form->control('email');
            echo $this->Form->control('iban');
            if ($isAdmin) {
                echo $this->Form->control('balance');
            }
            echo $this->Form->control('password');
            if ($isAdmin) {
                echo $this->Form->control('role_id', ['options' => $roles]);
                echo $this->Form->control('active');
            }
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Users/login.ctp
<h1>Login</h1>
<?= $this->Form->create() ?>
<?= $this->Form->control('email') ?>
<?= $this->Form->control('password') ?>
<?= $this->Form->button('Login') ?>
<?= $this->Form->end() ?>

src/Template/Users/register.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\User $user
 */
?>
<div class="users form large-12 medium-12 columns content">
    <?= $this->Form->create($user) ?>
    <fieldset>
        <legend><?= __('Register User') ?></legend>
        <?php
            echo $this->Form->control('first_name');
            echo $this->Form->control('last_name');
            echo $this->Form->control('phone');
            echo $this->Form->control('email');
            echo $this->Form->control('iban');
            echo $this->Form->control('password');

            echo $this->Form->checkbox('GDPR', ['value' => 1]);
            echo $this->Form->label('GDPR', 'Let op, bij het registreren van een account ga je akkoord met dat je persoonlijke gegevens zichtbaar zijn voor medegebruikers.');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Users/view.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\User $user
 */
?>
<nav class="large-2 medium-3 columns" id="actions-sidebar">
    <?= $this->element('Menu/gebruiker-menu') ?>
</nav>
<div class="users view large-10 medium-9 columns content">
    <h3><?= h($user->id) ?></h3>
    <table class="vertical-table">
        <tr>
            <th scope="row"><?= __('First Name') ?></th>
            <td><?= h($user->first_name) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Last Name') ?></th>
            <td><?= h($user->last_name) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Phone') ?></th>
            <td><?= h($user->phone) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Email') ?></th>
            <td><?= h($user->email) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Iban') ?></th>
            <td><?= h($user->iban) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Password') ?></th>
            <td><?= h($user->password) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Role') ?></th>
            <td><?= $user->has('role') ? $this->Html->link($user->role->name, ['controller' => 'Roles', 'action' => 'view', $user->role->id]) : '' ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Id') ?></th>
            <td><?= $this->Number->format($user->id) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Balance') ?></th>
            <td><?= $this->Number->currency($user->balance, 'EUR') ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Created') ?></th>
            <td><?= h($user->created) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Modified') ?></th>
            <td><?= h($user->modified) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Active') ?></th>
            <td><?= $user->active ? __('Yes') : __('No'); ?></td>
        </tr>
    </table>
    <div class="related">
        <h4><?= __('Related Purchase Orders') ?></h4>
        <?php if (!empty($user->purchase_orders)): ?>
        <table>
            <tr>
                <th scope="col"><?= __('Id') ?></th>
                <th scope="col"><?= __('Supplier Name') ?></th>
                <th scope="col"><?= __('User Name') ?></th>
                <th scope="col"><?= __('Delivery') ?></th>
                <th scope="col"><?= __('Delivery Moment') ?></th>
                <th scope="col"><?= __('Delivery Cost') ?></th>
                <th scope="col"><?= __('Total Amount') ?></th>
                <th scope="col"><?= __('Comment') ?></th>
                <th scope="col"><?= __('Closed') ?></th>
                <th scope="col"><?= __('Created') ?></th>
                <th scope="col"><?= __('Modified') ?></th>
                <th scope="col" class="actions"><?= __('Actions') ?></th>
            </tr>
            <?php foreach ($user->purchase_orders as $purchaseOrders): ?>
            <tr>
                <td><?= h($purchaseOrders->id) ?></td>
                <td><?= h($purchaseOrders->supplier->name) ?></td>
                <td><?= h($purchaseOrders->user->first_name.' '.$purchaseOrders->user->last_name) ?></td>
                <td><?= $purchaseOrders->delivery ? __('Yes') : __('No') ?></td>
                <td><?= h($purchaseOrders->delivery_moment) ?></td>
                <td><?= $this->Number->currency($purchaseOrders->delivery_cost, 'EUR') ?></td>
                <td><?= $this->Number->currency($purchaseOrders->total_amount, 'EUR') ?></td>
                <td><?= h($purchaseOrders->comment) ?></td>
                <td><?= $purchaseOrders->closed ? __('Yes') : __('No') ?></td>
                <td><?= h($purchaseOrders->created) ?></td>
                <td><?= h($purchaseOrders->modified) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['controller' => 'PurchaseOrders', 'action' => 'view', $purchaseOrders->id]) ?>
                    <?php if (!$purchaseOrders->closed): ?>
                        <?= $this->Html->link(__('Edit'), ['controller' => 'PurchaseOrders', 'action' => 'edit', $purchaseOrders->id]) ?>
                        <?= $this->Form->postLink(__('Delete'), ['controller' => 'PurchaseOrders', 'action' => 'delete', $purchaseOrders->id], ['confirm' => __('Are you sure you want to delete # {0}?', $purchaseOrders->id)]) ?>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?php endif; ?>
    </div>
    <div class="related">
        <h4><?= __('Related Suppliers Products Purchase Orders') ?></h4>
        <?php if (!empty($user->suppliers_products_purchase_orders)): ?>
        <table>
            <tr>
                <th scope="col"><?= __('Id') ?></th>
                <th scope="col"><?= __('Product Name') ?></th>
                <th scope="col"><?= __('Order No.') ?></th>
                <th scope="col"><?= __('User Name') ?></th>
                <th scope="col"><?= __('Quantity') ?></th>
                <th scope="col"><?= __('Price') ?></th>
                <th scope="col"><?= __('Comment') ?></th>
                <th scope="col"><?= __('Paid') ?></th>
                <th scope="col"><?= __('Created') ?></th>
                <th scope="col"><?= __('Modified') ?></th>
                <th scope="col" class="actions"><?= __('Actions') ?></th>
            </tr>
            <?php foreach ($user->suppliers_products_purchase_orders as $suppliersProductsPurchaseOrders): ?>
            <tr>
                <td><?= h($suppliersProductsPurchaseOrders->id) ?></td>
                <td><?= h($suppliersProductsPurchaseOrders->suppliers_product->product->name) ?></td>
                <td><?= h($suppliersProductsPurchaseOrders->purchase_order_id) ?></td>
                <td><?= h($suppliersProductsPurchaseOrders->user->first_name.' '.$suppliersProductsPurchaseOrders->user->last_name) ?></td>
                <td><?= h($suppliersProductsPurchaseOrders->quantity) ?></td>
                <td><?= $this->Number->currency($suppliersProductsPurchaseOrders->price, 'EUR') ?></td>
                <td><?= h($suppliersProductsPurchaseOrders->comment) ?></td>
                <td><?= $suppliersProductsPurchaseOrders->paid ? __('Yes') : __('No') ?></td>
                <td><?= h($suppliersProductsPurchaseOrders->created) ?></td>
                <td><?= h($suppliersProductsPurchaseOrders->modified) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['controller' => 'SuppliersProductsPurchaseOrders', 'action' => 'view', $suppliersProductsPurchaseOrders->id]) ?>
                    <?php if (!$suppliersProductsPurchaseOrders->paid): ?>
                        <?= $this->Html->link(__('Edit'), ['controller' => 'SuppliersProductsPurchaseOrders', 'action' => 'edit', $suppliersProductsPurchaseOrders->id]) ?>
                        <?= $this->Form->postLink(__('Delete'), ['controller' => 'SuppliersProductsPurchaseOrders', 'action' => 'delete', $suppliersProductsPurchaseOrders->id], ['confirm' => __('Are you sure you want to delete # {0}?', $suppliersProductsPurchaseOrders->id)]) ?>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?php endif; ?>
    </div>
</div>